import { UnifiedReport } from "../orchestrator/types";

export function generateGitHubComment(report: UnifiedReport): string {
  let markdown = `## ReviewFlow AI Analysis
> **Recommendation:** ${report.recommendation} | **Score:** ${report.score}/100

### Executive Summary
${report.executiveSummary}

---

### Findings
`;

  if (!report.deduplicatedFindings || report.deduplicatedFindings.length === 0) {
    markdown += `\n*No critical issues found! Everything looks clean.*`;
  } else {
    markdown += `| Severity | File | Line | Message |\n`;
    markdown += `|----------|------|------|---------|\n`;
    report.deduplicatedFindings.forEach(f => {
      const lineStr = f.line ? `L${f.line}` : "N/A";
      const cleanMessage = f.message.replace(/\n/g, "<br>").replace(/\|/g, "\\|");
      markdown += `| \`${f.severity}\` | \`${f.filePath}\` | \`${lineStr}\` | ${cleanMessage} |\n`;
    });
  }

  markdown += `\n\n<sub>*Automatically generated by ReviewFlow AI.*</sub>`;
  return markdown;
}
